=== rish4522/WSD/lab4/top.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.example.org/sample" 
xmlns:mca="http://www.example.org/sample" elementFormDefault="qualified">
<xs:element name="course">
<xs:complexType>
<xs:sequence>
    <xs:element name="student" minOccurs="1" maxOccurs="5">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>    
                <xs:element name="regno" type="mca:MyMarks"/>
                <xs:element name="class" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:simpleType name="MyMarks">
    <xs:restriction base="xs:integer">
    <xs:minInclusive value="1"></xs:minInclusive>
    <xs:maxInclusive value="99999999"></xs:maxInclusive>
 </xs:restriction> 
 </xs:simpleType>

</xs:schema>

=== rish4522/WSD/lab4/lab4.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="teststyle.xsl"?>
<course xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.example.org/sample top.xsd"> 
<student>
    <name>Rishabh</name>
    <regno>30</regno>
    <class>MCA</class>
</student> 
<student>
    <name>Abhishek</name>
    <regno>25</regno>
    <class>MSc</class>
</student> 
<student>
    <name>Akshaya</name>
    <regno>7</regno>
    <class>MCA</class>
</student> 
<student>
    <name>Vibha</name>
    <regno>56</regno>
    <class>BSc CEP</class>
</student> 
<student>
    <name>Anindita</name>
    <regno>13</regno>
    <class>BSc PSEng</class>
</student> 
</course>
