=== rish4522/WSD/CAT1/lab.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/sample" xmlns:rt="http://www.example.org/sample"
elementFormDefault="qualified">
    <xs:element name="company">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="employee" minOccurs="1" maxOccurs="10">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="emp_name" type="xs:string"/>
                            <xs:element name="emp_age" type="xs:integer"/>
                            <xs:element name="emp_salary" type="xs:long"/>
                            <xs:element name="emp_emailid" type="xs:string"/>
                            <xs:element name="emp_phonenum" type="xs:long"/>
                            <xs:element name="emp_designation" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>

                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="emp_salary">
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minInclusive value="50000"></xs:minInclusive>
                            <xs:maxInclusive value="200000"></xs:maxInclusive>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
</xs:schema>

=== rish4522/WSD/CAT1/lab.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="lab.xsl" type="text/xsl"?>
<company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/sample lab.xsd">
<employee>
    <emp_name>John Joseph</emp_name>
    <emp_age>32</emp_age>
    <emp_salary>70000</emp_salary>
    <emp_emailid>johnjosephemp@gmail.com</emp_emailid>
    <emp_phonenum>1234567890</emp_phonenum>
    <emp_designation>Manager</emp_designation>
</employee>
<employee>
    <emp_name>Abhishek Sharma</emp_name>
    <emp_age>27</emp_age>
    <emp_salary>95000</emp_salary>
    <emp_emailid>abhisheksharmaemp@gmail.com</emp_emailid>
    <emp_phonenum>9988556633</emp_phonenum>
    <emp_designation>Jr. Manager</emp_designation>
</employee>
<employee>
    <emp_name>Shyam Kapoor</emp_name>
    <emp_age>54</emp_age>
    <emp_salary>195000</emp_salary>
    <emp_emailid>shyamkapooremp@gmail.com</emp_emailid>
    <emp_phonenum>4455889922</emp_phonenum>
    <emp_designation>Executive Director</emp_designation>
</employee>
<employee>
    <emp_name>Robert Mill</emp_name>
    <emp_age>46</emp_age>
    <emp_salary>145000</emp_salary>
    <emp_emailid>robertmillemp@gmail.com</emp_emailid>
    <emp_phonenum>7755881103</emp_phonenum>
    <emp_designation>HR Manager</emp_designation>
</employee>
<employee>
    <emp_name>Test Case 1</emp_name>
    <emp_age>46</emp_age>
    <emp_salary>45000</emp_salary>
    <emp_emailid>testcaseemp@gmail.com</emp_emailid>
    <emp_phonenum>9989152102</emp_phonenum>
    <emp_designation>Team Lead</emp_designation>
</employee>
</company>
